name: flutter_inapp_purchase
description: In App Purchase plugin for flutter. This project has been forked by
  react-native-iap and we are willing to share same experience with that on
  react-native.
version: 5.3.1
homepage: https://github.com/dooboolab/flutter_inapp_purchase/blob/main/pubspec.yaml
environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.12.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: '>=0.11.0 <1.0.0'
  meta: 1.3.0-nullsafety.3
  platform: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.1
  test: ^1.16.5

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: com.dooboolab.flutterinapppurchase
        pluginClass: FlutterInappPurchasePlugin
        mainClass: FlutterInappPurchasePlugin
      ios:
        pluginClass: FlutterInappPurchasePlugin
